#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# build
echo -e "${YELLOW}Running pre-commit hook, dotnet build...${NC}"
dotnet build
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Failed to build the project, please fix this and commit again${NC}"
    exit $rc
fi

# test
echo -e "${YELLOW}Running pre-commit hook, dotnet test...${NC}"
dotnet test --no-build
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Test failed, please fix this and commit again${NC}"
    exit $rc
fi

# format
echo -e "${YELLOW}Running pre-commit hook, dotnet format...${NC}"
dotnet format --no-restore --verbosity detailed
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Failed to format project, please fix this and commit again${NC}"
    exit $rc
fi

exit 0
One thing that could be improved
