//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonArchiver.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonArchiver.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: &quot;no_armor&quot;,
        ///        &quot;name&quot;: &quot;No Armor&quot;,
        ///        &quot;type&quot;: &quot;No Armor&quot;,
        ///        &quot;rarity&quot;: &quot;Standard&quot;,
        ///        &quot;ac&quot;: 10,
        ///        &quot;cost&quot;: &quot;5 gp&quot;,
        ///        &quot;modifier&quot;: [
        ///            {
        ///                &quot;ability&quot;: &quot;dexterity&quot;,
        ///                &quot;max&quot;: null
        ///            }
        ///        ],
        ///        &quot;requirements&quot;: {},
        ///        &quot;disadvantage&quot;: false
        ///    },
        ///    {
        ///        &quot;id&quot;: &quot;padded_armour&quot;,
        ///        &quot;name&quot;: &quot;Padded Armor&quot;,
        ///        &quot;type&quot;: &quot;Light Armor&quot;,
        ///        &quot;rarity&quot;: &quot;Standard&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string armor {
            get {
                return ResourceManager.GetString("armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Acolyte&quot;,
        ///        &quot;desc&quot;: &quot;You have spent your life in the service of a temple to a specific god or pantheon of gods. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine. You are not necessarily a cleric-performing sacred rites is not the same thing as channeling divine power.\n\nChoose a god, a pantheon of gods, or some other quasi-divine bein [rest of string was truncated]&quot;;.
        /// </summary>
        public static string backgrounds {
            get {
                return ResourceManager.GetString("backgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Barbarian&quot;,
        ///        &quot;features&quot;: {
        ///            &quot;hit-dice&quot;: &quot;1d12&quot;,
        ///            &quot;hp-at-1st-level&quot;: &quot;12 + your Constitution modifier&quot;,
        ///            &quot;hp-at-higher-levels&quot;: &quot;1d12 (or 7) + your Constitution modifier per barbarian level after 1st&quot;,
        ///            &quot;prof-armor&quot;: &quot;Light armor, medium armor, shields&quot;,
        ///            &quot;prof-weapons&quot;: &quot;Simple weapons, martial weapons&quot;,
        ///            &quot;prof-tools&quot;: &quot;None&quot;,
        ///            &quot;prof-saving-throws&quot;: &quot;Strength, Constitution&quot;,
        ///            &quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Blinded&quot;,
        ///        &quot;desc&quot;: &quot;* A blinded creature can&apos;t see and automatically fails any ability check that requires sight.\n* Attack rolls against the creature have advantage, and the creature&apos;s attack rolls have disadvantage.&quot;
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Charmed&quot;,
        ///        &quot;desc&quot;: &quot;* A charmed creature can&apos;t attack the charmer or target the charmer with harmful abilities or magical effects.\n* The charmer has advantage on any ability check to interact socially with the creatu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string conditions {
            get {
                return ResourceManager.GetString("conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;title&quot;: &quot;Systems Reference Document&quot;,
        ///        &quot;slug&quot;: &quot;wotc-srd&quot;,
        ///        &quot;desc&quot;: &quot;Dungeons and Dragons 5th Edition Systems Reference Document by Wizards of the Coast&quot;,
        ///        &quot;license&quot;: &quot;Open Gaming License&quot;,
        ///        &quot;author&quot;: &quot;Mike Mearls, Jeremy Crawford, Chris Perkins, Rodney Thompson, Peter Lee, James Wyatt, Robert J. Schwalb, Bruce R. Cordell, Chris Sims, and Steve Townshend, based on original material by E. Gary Gygax and Dave Arneson.&quot;,
        ///        &quot;organization&quot;: &quot;Wizards of th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Grappler&quot;,
        ///        &quot;prerequisite&quot;: &quot;Strength 13 or higher&quot;,
        ///        &quot;desc&quot;: &quot;You&apos;ve developed the skills necessary to hold your own in close-quarters grappling. You gain the following benefits:\n- You have advantage on attack rolls against a creature you are grappling.\n- You can use your action to try to pin a creature grappled by you. To do so, make another grapple check. If you succeed, you and the creature are both restrained until the grapple ends.&quot;
        ///    }
        ///].
        /// </summary>
        public static string feats {
            get {
                return ResourceManager.GetString("feats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Adamantine Armor&quot;,
        ///        &quot;desc&quot;: &quot;This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you&apos;re wearing it, any critical hit against you becomes a normal hit.&quot;,
        ///        &quot;type&quot;: &quot;Armor (medium or heavy)&quot;,
        ///        &quot;rarity&quot;: &quot;uncommon&quot;
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Amulet of Health&quot;,
        ///        &quot;desc&quot;: &quot;Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is already 19 or higher.&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string magicitems {
            get {
                return ResourceManager.GetString("magicitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Aboleth&quot;,
        ///        &quot;size&quot;: &quot;Large&quot;,
        ///        &quot;type&quot;: &quot;aberration&quot;,
        ///        &quot;subtype&quot;: &quot;&quot;,
        ///        &quot;alignment&quot;: &quot;lawful evil&quot;,
        ///        &quot;armor_class&quot;: 17,
        ///        &quot;hit_points&quot;: 135,
        ///        &quot;hit_dice&quot;: &quot;18d10+36&quot;,
        ///        &quot;speed&quot;: &quot;10 ft., swim 40 ft.&quot;,
        ///        &quot;strength&quot;: 21,
        ///        &quot;dexterity&quot;: 9,
        ///        &quot;constitution&quot;: 15,
        ///        &quot;intelligence&quot;: 18,
        ///        &quot;wisdom&quot;: 15,
        ///        &quot;charisma&quot;: 18,
        ///        &quot;constitution_save&quot;: 6,
        ///        &quot;intelligence_save&quot;: 8,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monsters {
            get {
                return ResourceManager.GetString("monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;The Material Plane&quot;,
        ///        &quot;desc&quot;: &quot;The Material Plane is the nexus where the philosophical and elemental forces that define the other planes collide in the jumbled existence of mortal life and mundane matter. All fantasy gaming worlds exist within the Material Plane, making it the starting point for most campaigns and adventures. The rest of the multiverse is defined in relation to the Material Plane.\nThe worlds of the Material Plane are infinitely diverse, for they reflect t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string planes {
            get {
                return ResourceManager.GetString("planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Dwarf&quot;,
        ///        &quot;desc&quot;: &quot;## Dwarf Traits\nYour dwarf character has an assortment of inborn abilities, part and parcel of dwarven nature.&quot;,
        ///        &quot;asi-desc&quot;: &quot;**_Ability Score Increase._** Your Constitution score increases by 2.&quot;,
        ///        &quot;asi&quot;: [
        ///            {
        ///                &quot;attributes&quot;: [
        ///                    &quot;Constitution&quot;
        ///                ],
        ///                &quot;value&quot;: 2
        ///            }
        ///        ],
        ///        &quot;age&quot;: &quot;**_Age._** Dwarves mature at the same rate as humans, but [rest of string was truncated]&quot;;.
        /// </summary>
        public static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Planes&quot;,
        ///        &quot;desc&quot;: &quot;The cosmos teems with a multitude of worlds as well as myriad alternate dimensions of reality, called the **planes of existence**. It encompasses every world where GMs run their adventures, all within the relatively mundane realm of the Material Plane. Beyond that plane are domains of raw elemental matter and energy, realms of pure thought and ethos, the homes of demons and angels, and the dominions of the gods.\n\nMany spells and magic items can draw en [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sections {
            get {
                return ResourceManager.GetString("sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Acid Arrow&quot;,
        ///        &quot;desc&quot;: &quot;A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.&quot;,
        ///        &quot;higher_level&quot;: &quot;When you cast this spell using a spell slot of 3r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string spells {
            get {
                return ResourceManager.GetString("spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Club&quot;,
        ///        &quot;category&quot;: &quot;Simple Melee Weapons&quot;,
        ///        &quot;cost&quot;: &quot;1 sp&quot;,
        ///        &quot;damage_dice&quot;: &quot;1d4&quot;,
        ///        &quot;damage_type&quot;: &quot;bludgeoning&quot;,
        ///        &quot;weight&quot;: &quot;2 lb.&quot;,
        ///        &quot;properties&quot;: [
        ///            &quot;light&quot;
        ///        ]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Dagger&quot;,
        ///        &quot;category&quot;: &quot;Simple Melee Weapons&quot;,
        ///        &quot;cost&quot;: &quot;2 gp&quot;,
        ///        &quot;damage_dice&quot;: &quot;1d4&quot;,
        ///        &quot;damage_type&quot;: &quot;piercing&quot;,
        ///        &quot;weight&quot;: &quot;1 lb.&quot;,
        ///        &quot;properties&quot;: [
        ///            &quot;finesse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string weapons {
            get {
                return ResourceManager.GetString("weapons", resourceCulture);
            }
        }
    }
}
